apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo-svc
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http

